on: 
  push:
    branches:
      - master
jobs:
  CopyFilesToBackend:
    runs-on: ubuntu-latest
    name: Telling Server to fetch and rebuild...
    steps:
    - name: CopyCat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.COPYCAT_ACTION_KEY }}
        src_path: /src/components/
        dst_path: /app/javascript/components
        src_branch: master
        dst_branch: updateReactComponents
        dst_owner: UnifiedCalculation
        dst_repo_name: UniCalc_backend
